services:
#    acme_demo.example:
#        class: Acme\DemoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
      acme_demo.form.type.task:
          class: Acme\DemoBundle\Form\Type\AddressType
          tags:
              - { name: form.type, alias: address }
